### ISSUE TITLE
Multiple bib files?

### ISSUE THREAD

**Issue by jobindj** [shyamd/mkdocs-bibtex#11]
The `test-files` suggest that multiple bib files can be used with this plugin. I was trying to use multiple bib files by specifying the bib files as a list in the YAML file. But that doesn't seem to work. 

If it is possible to use multiple bib files, it would be helpful to know how I should define it in the YAML file. Thank you!

**Comment by shyamd** [comment]
You use the `bib_dir` argument to provide it the directory of bibtex files to use.
