### ISSUE TITLE
What license is this?

### ISSUE THREAD

**Issue by pawamoy** [shyamd/mkdocs-bibtex#119]
It seems tools have difficulty detecting which license this project is using? Is this BSD? MIT? Custom license?
I'm opening this to improve data displayed at https://github.com/pawamoy/best-of-mkdocs :slightly_smiling_face:

**Comment by sondregronas** [comment]
Seems to be a BSD variant (LBNL BSD) from the looks of it, https://spdx.org/licenses/BSD-3-Clause-LBNL.html matches

**Comment by shyamd** [comment]
Thanks sondregronas. Does this still need clarification or can we close it?

**Comment by pawamoy** [comment]
We can close, thank you both :slightly_smiling_face:
