### ISSUE TITLE
No longer supports bibtex keys with ":"

### ISSUE THREAD

**Issue by burp** [shyamd/mkdocs-bibtex#130]
Hi,

since version 2.0.0 citations with colons in the bibtex key are no longer parsed/recognized. Version 1.2.0 was the last version where this worked.

[@author:1234] works in 1.2.0 but not in 2.0.0 and newer.

Thanks,
Tobias

**Comment by shyamd** [comment]
Thanks for bringing this up. Can I ask what the use-case for the colon in the citation is? Is this a feature of some CSL style or just a colon in the name of the bibtex entry?

**Comment by burp** [comment]
It's just a colon in the name of the bibtex key. The de-facto standard website to get bibtex information about research papers in my field exports them with keys "Name:YearXYZ". Obviously I could remove the colon, but if this is a bug you acknowledge, it would be great to have fixed.

**Comment by shyamd** [comment]
Newest release should have fixed your issue.
