### ISSUE TITLE
Extra regex artefact in formatted output

### ISSUE THREAD

**Issue by NixImagery** [shyamd/mkdocs-bibtex#149]
When csl file is defined, footnote citations are rendered with what looks like extra characters perhaps left over from regex operations.

**Expected output** (get this with no `csl_file` defined)

Richard P. Feynman, Robert B. Leighton, and Matthew Sands. The Feynman Lectures on Physics. Addison-Wesley, Reading, MA, 1963. URL: http://www.feynmanlectures.caltech.edu/.

**Obtained output** (if `csl_file` is defined)

Feynman, R. P., Leighton, R. B., & Sands, M. (1963). [The Feynman Lectures on Physics]{.nocase}. Addison-Wesley. http://www.feynmanlectures.caltech.edu/.

Notice the extra square brackets around the document title, followed immediately by `{.nocase}`.

I'd like to use an external csl file and `cite_inline` which requires csl_file to be defined. Any ideas? Thanks.

**Comment by sondregronas** [comment]
PR #141 should've resolved this, are you running the latest version of the plugin?

If that's not the case, would you be able to provide the version of Pandoc installed, aswell as the bibentry and CSL file? I haven't been able to reproduce the issue on the latest release myself.

**Comment by NixImagery** [comment]
Apologies. This is fixed -- I had not upgraded to the latest version of the plugin (and `mkdocs-material`). Once I had done that, all works beautifully, thanks.
