### ISSUE TITLE
Missing dependency `pkg_resources`

### ISSUE THREAD

**Issue by matteosantama** [shyamd/mkdocs-bibtex#160]
The library depends on `pkg_resources` but it is not listed in `requirements.txt` so after `pip install mkdocs-bibtex` I'm getting 

```python
import mkdocs_bibtex

File ~/Library/Caches/pypoetry/virtualenvs/mfglib-SRAM7qJs-py3.9/lib/python3.9/site-packages/mkdocs_bibtex/__init__.py:1
----> 1 from pkg_resources import DistributionNotFound, get_distribution
      3 from mkdocs_bibtex.plugin import BibTexPlugin
      5 try:

ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by matteosantama** [comment]
Ah, it's not `pkg_resources` that's actually missing -- it's `setuptools`. After `pip install setuptools` it works.

**Comment by shyamd** [comment]
Oh! This is quite the interesting development. I'm assuming you're using this in a package where you use `poetry` instead of `setuptools`?

**Comment by matteosantama** [comment]
Yes, that’s right!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shyamd** [comment]
Ok, I know the issue. Its odd, but i can fix it. Let me do some repository cleanup and i'll take care of this issue.

**Comment by shyamd** [comment]
The latest release: `v2.8.6` should fix this. Let me know if you're still having issues. I only tried a simple dummy poetry package and I might have gotten it wrong.

**Comment by shyamd** [comment]
Correction, it turned out to be `v2.8.8` due to some hiccups fixing GH actions.

**Comment by matteosantama** [comment]
Hi @shyamd, thanks for looking into this. Unfortunately I am still running into the error with v2.8.8.

When I add an explicit `setuptools = "^65.6.3"` dependency, `mkdocs serve` runs fine.

**Comment by matteosantama** [comment]
I would think in `setup.py` you need to add `setuptools` [here](https://github.com/shyamd/mkdocs-bibtex/blob/main/setup.py#L19-L25) (although admittedly I am not very familiar with using a `setup.py` file for manually building packages).
