### ISSUE TITLE
Minor incompatibility with pymdown.arithmatex

### ISSUE THREAD

**Issue by lukas-koschmieder** [shyamd/mkdocs-bibtex#3]
The [pymdownx.arithmatex](https://squidfunk.github.io/mkdocs-material/extensions/pymdown/) extension may inject some MathJax code into the \bibliography section resulting in some characters being rendered as inline LaTeX code.

![mkdocs-bibtex](https://user-images.githubusercontent.com/31916683/64613481-81768100-d3d6-11e9-9376-fc7a5bddc33c.png)

**Comment by shyamd** [comment]
Yikes. Just saw this.

It's not obvious to me what the original bibtex would have to look like to cause this. Can you post that?

**Comment by 1one-w01f** [comment]
I encountered a similar problem. Basically if a bibtex entry has `(` and `)`, the underlying rendering backend escapes them into `\(` and `\)`, which then triggers the inline mode of [pymdownx.arithmatex](https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/).

Here's a bibtex that I used for testing, in case it helps:
```
@inproceedings{bock2018return,
  title={{Return Of Bleichenbacher’s Oracle Threat ({ROBOT})}},
  author={B{\"o}ck, Hanno and Somorovsky, Juraj and Young, Craig},
  booktitle={27th USENIX Security Symposium (USENIX Security 18)},
  pages={817--849},
  year={2018}
}
```

**Comment by 1one-w01f** [comment]
I added an option of `unescape_for_arithmatex` to let users opt-in for a simple hack (of replacing `\(` with `(` and `\)` with `)` in `entry_text` after line 155) 
https://github.com/shyamd/mkdocs-bibtex/blob/a7d0a3c9947bc8bb99b09be039b0f793b284e9d8/mkdocs_bibtex/plugin.py#L155
A pull request has been created, which also addresses issue #72. See if you're OK with it.

**Comment by shyamd** [comment]
This should be taken care of by default in the new release. Breaking out the `pybtex` formatting from the pandoc formatting let me figure out that `pybtex` backslashes ALL special characters. So, now it unbackslashes parenthesis and periods.
