### ISSUE TITLE
in-text references instead of footnotes?

### ISSUE THREAD

**Issue by jboynyc** [shyamd/mkdocs-bibtex#41]
I tried different CSL formats but they all seem to create footnotes. Is there a way to have the plugin create in-text references like (Author 2019) instead?

**Comment by shyamd** [comment]
Hi @jboynyc 

Do you mean you don't want the footnotes at all or just that the link is in `(Author 2019)` format rather than the default small number you get from footnotes?

**Comment by jboynyc** [comment]
No footnotes at all. Ideally the in-text reference would just link to the bibliography item.

**Comment by shyamd** [comment]
Ah, that's not currently possible. The pull request #39 sort of gets what you want, but it also breaks some current behavior which is why it's not being merged in yet. That would be a place to start if you'd be willing to contribute code.

**Comment by jboynyc** [comment]
OK, good to know! Thanks. I'll look through the code a bit when I get a chance to see whether I can contribute. For now I'll close this.
