### ISSUE TITLE
options csl_file and cite_style don't seem to be effective

### ISSUE THREAD

**Issue by 1one-w01f** [shyamd/mkdocs-bibtex#72]
I just realized that the options `csl_file` and `cite_style` don't seem to be functioning as expected. Should the `config.get()` actually be `self.config.get()` in the following lines? I changed the code this way and then the 2 options appear to be working again.
https://github.com/shyamd/mkdocs-bibtex/blob/a7d0a3c9947bc8bb99b09be039b0f793b284e9d8/mkdocs_bibtex/plugin.py#L73
https://github.com/shyamd/mkdocs-bibtex/blob/a7d0a3c9947bc8bb99b09be039b0f793b284e9d8/mkdocs_bibtex/plugin.py#L84

**Comment by shyamd** [comment]
Thanks. This was released in `v0.4.0`.

**Comment by roaldarbol** [comment]
This is still not working properly for me unfortunately. I've now tried 3 different `.csl` styles (including the good ol' `apa`), but they all cut my bibliography short, e.g here with and without specifying a `.csl` file:
<img width="531" alt="Screenshot 2021-06-21 at 18 37 06" src="https://user-images.githubusercontent.com/25629697/122804356-bdcf5480-d2bf-11eb-9421-920be0d6ca70.png">
<img width="970" alt="Screenshot 2021-06-21 at 18 36 54" src="https://user-images.githubusercontent.com/25629697/122804370-c0ca4500-d2bf-11eb-9152-d9b529e2fdd5.png">

Is it also supposed to modify the inline citation style? Mine shows up as [^1], but according to the `.csl` styles they should be author-date?

**Comment by shyamd** [comment]
The intention was to have the CSL style for formatting the bibliography reference. I would suggest you make a new issue for using the CSL style for the in-text citation reference, but it's not clear to me how to do this.

**Comment by roaldarbol** [comment]
I'll make a new issue for the inline citations. Any clue about the issue with the formatting?
I'm running MacOS Big Sur, in a conda environment.

<details>
<summary>Here's conda list:</summary>

# Name                    Version                   Build  Channel
ca-certificates           2021.5.30            h033912b_0    conda-forge
certifi                   2021.5.30        py39h6e9494a_0    conda-forge
citeproc-py               0.6.0                    pypi_0    pypi
click                     8.0.1                    pypi_0    pypi
ghp-import                2.0.1                    pypi_0    pypi
importlib-metadata        4.5.0                    pypi_0    pypi
jinja2                    3.0.1                    pypi_0    pypi
latexcodec                2.0.1                    pypi_0    pypi
libcxx                    10.0.0                        1  
libffi                    3.3                  hb1e8313_2  
lxml                      4.6.3                    pypi_0    pypi
markdown                  3.3.4                    pypi_0    pypi
markupsafe                2.0.1                    pypi_0    pypi
mergedeep                 1.3.4                    pypi_0    pypi
mkdocs                    1.2.1                    pypi_0    pypi
mkdocs-bibtex             0.4.0                    pypi_0    pypi
mkdocs-material           7.1.8                    pypi_0    pypi
mkdocs-material-extensions 1.0.1                    pypi_0    pypi
ncurses                   6.2                  h0a44026_1  
openssl                   1.1.1k               h0d85af4_0    conda-forge
packaging                 20.9                     pypi_0    pypi
pandoc                    2.14.0.2             h0d85af4_0    conda-forge
pip                       21.1.2           py39hecd8cb5_0  
pybtex                    0.24.0                   pypi_0    pypi
pygments                  2.9.0                    pypi_0    pypi
pymdown-extensions        8.2                      pypi_0    pypi
pypandoc                  1.5                pyh9f0ad1d_0    conda-forge
pyparsing                 2.4.7                    pypi_0    pypi
python                    3.9.5                h88f2d9e_3  
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.9                      1_cp39    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
pyyaml-env-tag            0.1                      pypi_0    pypi
readline                  8.1                  h9ed2024_0  
setuptools                52.0.0           py39hecd8cb5_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.35.4               hce871da_0  
tk                        8.6.10               hb0a8c7a_0  
tzdata                    2020f                h52ac0ba_0  
watchdog                  2.1.2                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h1de35cc_0  
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3  

</details>

**Comment by roaldarbol** [comment]
Also, including the footnotes extension made all the difference to me, so good shout for including it explicitly! 👍

**Comment by 1one-w01f** [comment]
I think the problem is partly due to [line 217 of plugin.py](https://github.com/shyamd/mkdocs-bibtex/blob/fdd881a6c70694a75be7c4c49723f3e1a8cb2ad3/mkdocs_bibtex/plugin.py#L217), which splits the string on `\n` and only returns the first element.

Whatever returned by pandoc might be broken into multiple lines, but this cannot be seen with the original short test entry in `single.bib`. As a quick and dirty workaround, replacing line 217 with `markdown = markdown.replace("\n", " ")[2:]` seems to work better.
