### ISSUE TITLE
pandoc-citeproc deprecated

### ISSUE THREAD

**Issue by roaldarbol** [shyamd/mkdocs-bibtex#75]
Hi there, thanks for a great plugin! I just updated my pandoc, and now I'm getting an error message trying to `mkdocs serve`: 

```RuntimeError: Pandoc died with exitcode "83" during conversion: b'[WARNING] Deprecated: pandoc-citeproc filter. Use --citeproc instead.\nError running filter pandoc-citeproc:\nCould not find executable pandoc-citeproc\n'```

It seeems to be caused by line 212 in `plugin.py` which specifies `filters=["pandoc-citeproc"]`. Importantly, `pandoc-citeproc` can no longer be downloaded with homebrew on Mac, so a new solution seems to be needed. I've tried a few things, and it seems that the fix is to remove `filters` and add `--citeproc` to  `extra_args` instead. I'll try to do a pull request (it'll be my first, so I need to learn *that* now ;-) ).

**Comment by shyamd** [comment]
You might be better off using the `conda-forge` version of `pypandoc`. I'm hesitant to do version based calling of `pandoc` unless we have a good feature need.

**Comment by roaldarbol** [comment]
Fair enough. Might be worth adding to the documentation then. 👍

**Comment by shyamd** [comment]
what do you get if you do this:
``` python
import shutil
import pypandoc

shutil.which("pandoc")
print(pypandoc.get_pandoc_version())
print(pypandoc.get_pandoc_path())
```

**Comment by roaldarbol** [comment]
I get:
```
2.14.0.2
pandoc
```
