### ISSUE TITLE
Compatibility with mkdocs-jupyter

### ISSUE THREAD

**Issue by DavidWalz** [shyamd/mkdocs-bibtex#94]
References in notebooks ([mkdocs-jupyter](https://github.com/danielfrg/mkdocs-jupyter)) are not picked up.

![image](https://user-images.githubusercontent.com/2913236/141696522-c9984266-708f-452f-94c7-588eb8595818.png)

Is there something about the order of notebook conversion and reference processing that could be done?

**Comment by shyamd** [comment]
Hmmm. This is odd because `mkdocs-jupyter` should be converting the notebook to markdown and then `mkdocs-bibtex` gets that markdown. Do you have a repo you're using this on that I can play with to test it out?

**Comment by shyamd** [comment]
Figured it out. `mkdocs-jupyter` skips all of markdown processing by directly rendering HTML. There's no way to put anything in-between to capture citations or any other type of processing.
See: https://github.com/danielfrg/mkdocs-jupyter/blob/3d90498f5fb61295d892754a12535866a0945c72/mkdocs_jupyter/plugin.py#L80

**Comment by shyamd** [comment]
Closing this as it's not something I can do anything about in this extension.

**Comment by DavidWalz** [comment]
Thank you for looking into this!
