### ISSUE TITLE
Pandoc style misses support for multiple keys

### ISSUE THREAD

**Issue by wadoon** [shyamd/mkdocs-bibtex#98]
Pandoc generates citations with multiple keys. For example, 

```
[@JMLReferenceManual11; @Leavens-Baker-Ruby04]
```

This plugin is not able to handle these citations. The [regex](https://github.com/shyamd/mkdocs-bibtex/blob/master/mkdocs_bibtex/plugin.py#L77) (and the succeeding code) is streamlined for the single-key usage case.

**Comment by shyamd** [comment]
Good point, I'll work on this after I update the python compatibility.

**Comment by shyamd** [comment]
This should be fixed in the latest release.
